name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: testFirstProgram
      id: testfirstprogram
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testFirstProgram
        setup-command: ''
        command: gradle test --tests FirstProgramTester.testFixError
        timeout: 1
        max-score: 4
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TESTFIRSTPROGRAM_RESULTS: "${{steps.testfirstprogram.outputs.result}}"
      with:
        runners: testfirstprogram
